unit ConfigCredenciais_Exemplo;

interface

const
  FTP_HOST = 'INSERIR_HOST_AQUI';
  FTP_USER = 'INSERIR_USUARIO_AQUI';
  FTP_PASS = 'INSERIR_SENHA_AQUI';
  SENHA_APP = 'INSERIR_SENHA_DO_APP_AQUI';
  SENHA_UPLOAD = 'INSERIR_SENHA_DO_APP_AQUI';
  SENHA_BACKUP = 'INSERIR_SENHA_BACKUP_AQUI';


implementation



end.
